# Generated by Django 4.1 on 2022-08-05 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EntityInAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='audio.audio')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='entity.entity')),
            ],
        ),
    ]
