# Generated by Django 4.1.2 on 2022-10-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("entity", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="discord_id",
            field=models.IntegerField(db_index=True, default=0),
        )
    ]
