# Generated by Django 4.1 on 2022-08-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='type',
        ),
        migrations.AddField(
            model_name='entity',
            name='discord_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entity',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EntityInAudio',
        ),
    ]
