# Generated by Django 4.1.2 on 2022-10-23 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("entity", "0003_remove_entity_server_entity_server")]

    operations = [
        migrations.RenameField(
            model_name="entity", old_name="server", new_name="servers"
        )
    ]
