# Generated by Django 4.1.2 on 2022-11-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("entity", "0004_rename_server_entity_servers")]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="discord_id",
            field=models.BigIntegerField(db_index=True, default=0),
        )
    ]
