# Generated by Django 4.1.2 on 2022-11-04 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0003_alter_server_discord_id"),
        ("entity", "0005_alter_entity_discord_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="entity", name="servers"),
        migrations.AddField(
            model_name="entity",
            name="servers",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entities",
                to="server.server",
            ),
        ),
    ]
