# Generated by Django 4.2.3 on 2024-09-29 00:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_rename_servers_entity_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
