# Generated by Django 4.1.2 on 2022-10-04 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("audio", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="audio",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 4, 15, 6, 56, 97339, tzinfo=datetime.timezone.utc
                )
            ),
        )
    ]
