# Generated by Django 4.1.2 on 2022-10-04 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("audio", "0002_audio_created_at")]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 4, 15, 57, 18, 775184, tzinfo=datetime.timezone.utc
                )
            ),
        )
    ]
