# Generated by Django 4.1.2 on 2022-10-04 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("audio", "0003_alter_audio_created_at")]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 4, 17, 13, 34, 47062, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="audio",
            name="hashcode",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="audioinentity",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="audioinserver",
            name="name",
            field=models.CharField(db_index=True, default="", max_length=20),
        ),
    ]
