# Generated by Django 4.1.2 on 2022-10-05 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0004_alter_audio_created_at_alter_audio_hashcode_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="audioinentity",
            name="volume",
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name="audioinserver",
            name="volume",
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="audio",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 5, 22, 46, 30, 164970, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
