# Generated by Django 4.1.2 on 2022-10-15 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audio", "0005_audioinentity_volume_audioinserver_volume_and_more")
    ]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="created_at",
            field=models.DateField(
                default=datetime.datetime(
                    2022, 10, 15, 3, 23, 26, 810559, tzinfo=datetime.timezone.utc
                )
            ),
        )
    ]
