# Generated by Django 4.1.2 on 2022-10-15 03:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("audio", "0006_alter_audio_created_at")]

    operations = [
        migrations.AlterField(
            model_name="audio",
            name="created_at",
            field=models.DateField(default=django.utils.timezone.now),
        )
    ]
