name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3
        name: Build the Docker image
        run: |
          sudo docker build .
          sudo docker run --name wavu --network="host" -d --restart always -v /home/pepi/wavu/audios:/app/audio wavu
