name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v3
    - name: Git pull changes
      run: |
        cd /home/pepi/wavu/wavU
        git pull

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd /home/pepi/wavu/wavU
        docker build --file ./Dockerfile -t wavu .
        docker stop wavu
        docker container prune -f
        docker run --name wavu --network="host" -d --restart always -v /home/pepi/wavu/audios:/app/audio wavu
        docker image prune -f