name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: FedericoCarboni/setup-ffmpeg@v2
      id: setup-ffmpeg
    - run: ffmpeg -i input.avi output.mkv

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        python service/manage.py migrate --settings=service.settings.production
        python service/manage.py runwavu --settings=service.settings.production
        