name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd
        sudo docker build --file ./wavu/wavU/Dockerfile -t wavu .
        sudo docker run --name wavu --network="host" -d --restart always -v /home/pepi/wavu/audios:/app/audio wavu
